### ISSUE TITLE
Android: Optimize error message when building with liveview for device when no device connected

### ISSUE THREAD

**Issue by jasonkneen** [tidev/titanium_mobile#13321]
Attempt a build specifying device as target and `--device-id 1` (so you get a selection list) and if no device is installed you get:

Ideally, this would be a better error.

```Continuing with build... (will attempt to install missing dependencies)

[LiveView] TypeError: Cannot read property 'once' of undefined
    at wireupPrePrompt (/Users/jkneen/.nvm/versions/node/v12.22.7/lib/node_modules/titanium/lib/cli.js:422:12)
    at /Users/jkneen/.nvm/versions/node/v12.22.7/lib/node_modules/titanium/lib/cli.js:591:21
    at /Users/jkneen/Library/Application Support/Titanium/mobilesdk/osx/10.1.1.GA/android/cli/commands/_build.js:420:17
    at AndroidBuilder.findTargetDevices (/Users/jkneen/Library/Application Support/Titanium/mobilesdk/osx/10.1.1.GA/android/cli/commands/_build.js:160:12)
    at prompt (/Users/jkneen/Library/Application Support/Titanium/mobilesdk/osx/10.1.1.GA/android/cli/commands/_build.js:377:8)
    at Object.opt.prompt (/Users/jkneen/.nvm/versions/node/v12.22.7/lib/node_modules/titanium/lib/cli.js:590:11)
    at /Users/jkneen/.nvm/versions/node/v12.22.7/lib/node_modules/titanium/lib/cli.js:849:9
    at /Users/jkneen/.nvm/versions/node/v12.22.7/lib/node_modules/titanium/node_modules/async/dist/async.js:4011:13
    at Object.process (/Users/jkneen/.nvm/versions/node/v12.22.7/lib/node_modules/titanium/node_modules/async/dist/async.js:1674:21)
    at /Users/jkneen/.nvm/versions/node/v12.22.7/lib/node_modules/titanium/node_modules/async/dist/async.js:1532:23
╭─     opus_app     dev-jason *3 !11                                                                                                                                                                                    ✔  11:10:08   
╰─ tn droid --target device --device-id 1 --liveview
```

**Comment by m1ga** [comment]
Error will appear without liveview too.
like to source https://github.com/tidev/titanium/blob/master/lib/cli.js#L422

a workaround/fix is to add
```js
if (field == undefined) {
  if (!opt._err) {
    _t.logger.error(__('Invalid "%s" value "%s"', (opt.label || '--' + name), argv[name]) + '\n');
  } else if (opt._err instanceof Error) {
    _t.logger.error(opt._err.message + '\n');
  } else if (typeof opt._err === 'string') {
    _t.logger.error(opt._err + '\n');
  }
}
```

it will log `[ERROR] Invalid Android device "1"` and run a "build only" build

**Comment by m1ga** [comment]
Fix: https://github.com/tidev/titanium/pull/557

**Comment by m1ga** [comment]
fix has been merged
