### ISSUE TITLE
iOS: optimize error message if installation fails

### ISSUE THREAD

**Issue by m1ga** [tidev/titanium_mobile#13349]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

When you try to install on a device that is not registered in your prov. profiles it will fail with a JS error after "installing app..".
It was pointing to that line: https://github.com/tidev/titanium_mobile/blob/master/iphone/cli/hooks/install.js#L207
but wasn't showing a proper error message.

Tested with 10.1.1.GA and 10.2.0

error message:
```
[ERROR] Error
    at Object.<anonymous> (/Users/miga/Library/Application Support/Titanium/mobilesdk/osx/10.2.0.v20220325163249/node_modules/node-appc/lib/exception.js:34:27)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.get (/Users/miga/Library/Application Support/Titanium/mobilesdk/osx/10.2.0.v20220325163249/node_modules/node-appc/lib/appc.js:62:11)
    at Handle.<anonymous> (/Users/miga/Library/Application Support/Titanium/mobilesdk/osx/10.2.0.v20220325163249/iphone/cli/hooks/install.js:207:22)
    at Handle.emit (events.js:412:35)
```

test:
* remove device from prov.profile
* build app for device

### Solution

Provide a proper error message "check prov. profiles or device".

### Platforms

iOS

**Comment by m1ga** [comment]
Error code is `0xe800001a` and message `Failed to transfer app to device` if we want to add an extra case.
But it is not even showing the default error anymore (it has an `else` case)
