### ISSUE TITLE
JNI Error in DateTimeFormatProxy.format(java.util.Date)

### ISSUE THREAD

**Issue by OBrown92** [tidev/titanium_mobile#13506]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

I've tried to integrate Temporal as an npm package to a titanium project and got the following Error:
```sh
JNI ERROR (app bug): attempt to pass an instance of java.lang.Double as argument 1 to java.lang.String ti.modules.titanium.locale.DateTimeFormatProxy.format(java.util.Date)
```
I've pass an `string` into the function.
This error is android only. On iOS it's working fine.

### Expected Behavior

The function
```js
plainDate.toLocaleString('en')
``` 
should deliver something like `1/1/2022`

### Actual behavior

```sh
JNI ERROR (app bug): attempt to pass an instance of java.lang.Double as argument 1 to java.lang.String ti.modules.titanium.locale.DateTimeFormatProxy.format(java.util.Date)
```

### Reproducible sample

```js
import { Temporal } from '@js-temporal/polyfill';
let temporal = Temporal.PlainDate.from('2022-01-01');
console.log(temporal.toLocaleString('en'))
```

### Steps to reproduce

Just try to compile the sample code on android

### Platform

Android

### SDK version you are using

11.0.0.RC

**Comment by m1ga** [comment]
Think it's the override in https://github.com/tidev/titanium_mobile/blob/master/common/Resources/ti.internal/extensions/js/Date.js#L68 or https://github.com/tidev/titanium_mobile/blob/b3256959bf84a6fb2e3e86554cdc0867f0d533c3/common/Resources/ti.internal/extensions/js/Number.js that is calling https://github.com/tidev/titanium_mobile/blob/f80e1dc35b7e1d8795fd096db2b350fddc94e88c/android/modules/locale/src/java/ti/modules/titanium/locale/DateTimeFormatProxy.java#L227

As a workaround: moment.js is included or 
```js
const text = new Intl.DateTimeFormat('en', { timeStyle: 'medium' }).format(new Date())
```

As a first test I've tried to add a second `format(String date)` function into the SDK. It is called but I'm not getting the right return value that temporal can use:
```
[] : (main) [274,274] /node_modules/@js-temporal/polyfill/dist/index.cjs:6212
[] : formatter.format(instant.epochMilliseconds)):
[] :           ^
[] : Error: Unknown Java Exception occurred
[] :     at DateTimeFormatImpl.format (/node_modules/@js-temporal/polyfill/dist/index.cjs:6212:11)
[] :     at PlainDate.toLocaleString (/node_modules/@js-temporal/polyfill/dist/index.cjs:6993:44)
[] :     at new Controller (/alloy/controllers/index.js:47:19)
[] :     at Object.exports.createController (/alloy.js:427:8)
```

but I'm not sure if we/I should do all the work to get an external lib to run if we have moment included and native JS methods to convert dates :rofl: 

Also check this thread on Slack: https://tidev.slack.com/archives/C03CVQX2A/p1657626396048689 where we talked about some issues in the current `toLocaleTimeString` method
