### ISSUE TITLE
Android: RecyclerView scroll update

### ISSUE THREAD

**Issue by m1ga** [tidev/titanium_mobile#13766]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

Scrolling a TableView that is updating results in this warning:

error
```
[WARN]  RecyclerView: Cannot call this method in a scroll callback. Scroll callbacks mightbe run during a measure & layout pass where you cannot change theRecyclerView data. Any method call that might change the structureof the RecyclerView or the adapter contents should be postponed tothe next frame.
[WARN]  RecyclerView: java.lang.IllegalStateException:  ti.modules.titanium.ui.widget.listview.TiNestedRecyclerView{c888b5 VFED.V... ......ID 0,0-1080,1801}, adapter:ti.modules.titanium.ui.widget.tableview.TableViewAdapter@78b4a, layout:ti.modules.titanium.ui.widget.tableview.TiTableView$1@4e30abb, context:android.view.ContextThemeWrapper@992bbd8
[WARN]  RecyclerView:   at androidx.recyclerview.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:3195)
[WARN]  RecyclerView:   at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeInserted(RecyclerView.java:5720)
[WARN]  RecyclerView:   at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyItemRangeInserted(RecyclerView.java:12684)
[WARN]  RecyclerView:   at androidx.recyclerview.widget.RecyclerView$Adapter.notifyItemRangeInserted(RecyclerView.java:7722)
[WARN]  RecyclerView:   at androidx.recyclerview.widget.AdapterListUpdateCallback.onInserted(AdapterListUpdateCallback.java:42)
[WARN]  RecyclerView:   at androidx.recyclerview.widget.BatchingListUpdateCallback.dispatchLastEvent(BatchingListUpdateCallback.java:61)
[WARN]  RecyclerView:   at androidx.recyclerview.widget.DiffUtil$DiffResult.dispatchUpdatesTo(DiffUtil.java:967)
[WARN]  RecyclerView:   at androidx.recyclerview.widget.DiffUtil$DiffResult.dispatchUpdatesTo(DiffUtil.java:840)
[WARN]  RecyclerView:   at ti.modules.titanium.ui.widget.listview.TiRecyclerViewAdapter.update(TiRecyclerViewAdapter.java:126)
[WARN]  RecyclerView:   at ti.modules.titanium.ui.widget.tableview.TiTableView.update(TiTableView.java:749)
[WARN]  RecyclerView:   at ti.modules.titanium.ui.TableViewProxy.update(TableViewProxy.java:1016)
[WARN]  RecyclerView:   at ti.modules.titanium.ui.TableViewProxy.update(TableViewProxy.java:1021)
[WARN]  RecyclerView:   at ti.modules.titanium.ui.TableViewProxy.setData(TableViewProxy.java:535)
[WARN]  RecyclerView:   at ti.modules.titanium.ui.TableViewProxy.setData(TableViewProxy.java:514)
[WARN]  RecyclerView:   at org.appcelerator.kroll.runtime.v8.V8Object.nativeFireEvent(Native Method)
[WARN]  RecyclerView:   at org.appcelerator.kroll.runtime.v8.V8Object.fireEvent(V8Object.java:63)
[WARN]  RecyclerView:   at org.appcelerator.kroll.KrollProxy.doFireEvent(KrollProxy.java:985)
[WARN]  RecyclerView:   at org.appcelerator.kroll.KrollProxy.fireSyncEvent(KrollProxy.java:819)
[WARN]  RecyclerView:   at org.appcelerator.titanium.proxy.TiViewProxy.fireSyncEvent(TiViewProxy.java:1037)
[WARN]  RecyclerView:   at org.appcelerator.titanium.proxy.TiViewProxy.fireSyncEvent(TiViewProxy.java:1043)
[WARN]  RecyclerView:   at ti.modules.titanium.ui.widget.tableview.TiTableView$2.onScrolled(TiTableView.java:138)
[WARN]  RecyclerView:   at androidx.recyclerview.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:5347)
[WARN]  RecyclerView:   at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5512)
[WARN]  RecyclerView:   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
[WARN]  RecyclerView:   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
[WARN]  RecyclerView:   at android.view.Choreographer.doCallbacks(Choreographer.java:899)
[WARN]  RecyclerView:   at android.view.Choreographer.doFrame(Choreographer.java:827)
[WARN]  RecyclerView:   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
[WARN]  RecyclerView:   at android.os.Handler.handleCallback(Handler.java:942)
[WARN]  RecyclerView:   at android.os.Handler.dispatchMessage(Handler.java:99)
[WARN]  RecyclerView:   at android.os.Looper.loopOnce(Looper.java:201)
[WARN]  RecyclerView:   at android.os.Looper.loop(Looper.java:288)
[WARN]  RecyclerView:   at android.app.ActivityThread.main(ActivityThread.java:7872)
[WARN]  RecyclerView:   at java.lang.reflect.Method.invoke(Native Method)
[WARN]  RecyclerView:   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
[WARN]  RecyclerView:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
[WARN]  W/ Cleared Reference was only reachable from finalizer (only reported once)
```

Possible fix: https://stackoverflow.com/a/59570583/5193915

Adding
```java
		recyclerView.post(new Runnable() {
			public void run()
			{
				adapter.update(rows, force);
			}
		});
```

here: https://github.com/tidev/titanium_mobile/blob/8a36570af01960804eb7d6c616f0b6ff300fd59a/android/modules/ui/src/java/ti/modules/titanium/ui/widget/tableview/TiTableView.java#L749

will get rid of the warning. 

PR soon

### Platform

Android

### SDK version you are using

12.0.0

**Comment by m1ga** [comment]
PR https://github.com/tidev/titanium_mobile/pull/13768
